//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWcf.MiServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MiServicio.IMiServicio")]
    public interface IMiServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/GetData", ReplyAction="http://tempuri.org/IMiServicio/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/GetData", ReplyAction="http://tempuri.org/IMiServicio/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/Bienvenido", ReplyAction="http://tempuri.org/IMiServicio/BienvenidoResponse")]
        string Bienvenido(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/Bienvenido", ReplyAction="http://tempuri.org/IMiServicio/BienvenidoResponse")]
        System.Threading.Tasks.Task<string> BienvenidoAsync(string nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMiServicioChannel : ClienteWcf.MiServicio.IMiServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MiServicioClient : System.ServiceModel.ClientBase<ClienteWcf.MiServicio.IMiServicio>, ClienteWcf.MiServicio.IMiServicio {
        
        public MiServicioClient() {
        }
        
        public MiServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MiServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string Bienvenido(string nombre) {
            return base.Channel.Bienvenido(nombre);
        }
        
        public System.Threading.Tasks.Task<string> BienvenidoAsync(string nombre) {
            return base.Channel.BienvenidoAsync(nombre);
        }
    }
}
